# Generated by Django 5.0.7 on 2024-09-26 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customers.companycontract'),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terminalservice'),
        ),
        migrations.AlterUniqueTogether(
            name='companycontract',
            unique_together={('company', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='contractservice',
            unique_together={('contract', 'service')},
        ),
    ]
