# Generated by Django 5.0.7 on 2024-09-27 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_size', models.CharField(choices=[('20', '20 ft Standard'), ('20HC', '20 ft High Cube'), ('40', '40 ft Standard'), ('40HC', '40 ft High Cube'), ('45', '45 ft High Cube')], max_length=50)),
                ('container_state', models.CharField(choices=[('loaded', 'loaded'), ('empty', 'empty')], max_length=6)),
                ('category', models.CharField(choices=[('import', 'Import'), ('export', 'Export'), ('transit', 'Transit')], max_length=10)),
                ('free_days', models.PositiveIntegerField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_day_categories', to='customers.companycontract')),
            ],
            options={
                'verbose_name': 'Free Day Category',
                'verbose_name_plural': 'Free Day Categories',
                'unique_together': {('contract', 'container_size', 'container_state', 'category')},
            },
        ),
    ]
