# Generated by Django 5.0.7 on 2024-09-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_freedaycategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontract',
            name='free_days',
        ),
    ]
