# Generated by Django 5.0.7 on 2024-09-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_freedaycombination_category_and_more'),
        ('customers', '0005_delete_freedaycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractFreeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_days', models.PositiveIntegerField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_free_days', to='customers.companycontract')),
                ('free_day_combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_free_days', to='core.freedaycombination')),
            ],
            options={
                'verbose_name': 'Contract Free Day',
                'verbose_name_plural': 'Contract Free Days',
                'unique_together': {('contract', 'free_day_combination')},
            },
        ),
    ]
