# Generated by Django 5.0.7 on 2024-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_companycontract_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='free_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
