exclude: .*migrations/\.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest-cov
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
          "--cov=apps",
          "--cov-report=term-missing",
          "--cov-fail-under=70",
          "tests/"
        ]
