version: '3.8'

services:
  web:
    build: .
    command: >
          sh -c "python manage.py makemigrations core &&
                 python manage.py makemigrations users &&
                 python manage.py makemigrations &&
                 python manage.py migrate &&
                 python create_superuser.py &&
                 python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=terminal  # Automatically create the 'terminal' database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1998
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  postgres_data:
