# Generated by Django 5.0.7 on 2024-09-26 05:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Container Name')),
                ('size', models.CharField(choices=[('20', '20 ft Standard'), ('20HC', '20 ft High Cube'), ('40', '40 ft Standard'), ('40HC', '40 ft High Cube'), ('45', '45 ft High Cube')], max_length=4, verbose_name='Container Type')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'db_table': 'container',
            },
        ),
        migrations.CreateModel(
            name='TerminalServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
                ('unit_of_measure', models.CharField(choices=[('container', 'container'), ('day', 'day'), ('operation', 'Operation'), ('piece', 'Piece')], max_length=50)),
            ],
            options={
                'verbose_name': 'Terminal Service Type',
                'verbose_name_plural': 'Terminal Service Types',
                'db_table': 'terminal_service_type',
            },
        ),
        migrations.CreateModel(
            name='TerminalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
                ('container_size', models.CharField(choices=[('20', '20 feet'), ('40', '40 feet'), ('20HC', '20 High Cube feet'), ('40HC', '40 High Cube feet'), ('45', '45 feet'), ('any', 'Any size')], default='ANY', max_length=50)),
                ('container_state', models.CharField(choices=[('loaded', 'Loaded'), ('empty', 'Empty'), ('any', 'Any state')], default='ANY', max_length=6)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.terminalservicetype')),
            ],
            options={
                'verbose_name': 'Terminal Service',
                'verbose_name_plural': 'Terminal Services',
                'unique_together': {('name', 'container_size', 'container_state')},
            },
        ),
    ]
