# Generated by Django 5.0.7 on 2024-09-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_freedaycombination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedaycombination',
            name='category',
            field=models.CharField(choices=[('import', 'Import'), ('export', 'Export'), ('transit', 'Transit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='freedaycombination',
            name='container_state',
            field=models.CharField(choices=[('loaded', 'loaded'), ('empty', 'empty')], max_length=50),
        ),
    ]
