# Generated by Django 5.0.7 on 2024-09-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_freedaycombination_test_free_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freedaycombination',
            name='test_free_days',
        ),
    ]
