# Generated by Django 5.0.7 on 2024-10-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_freedaycombination_container_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='size',
            field=models.CharField(choices=[('20', '20 ft Standard'), ('20HC', '20 ft High Cube'), ('40', '40 ft Standard'), ('40HC', '40 ft High Cube'), ('45', '45 ft High Cube'), ('any', 'any')], max_length=4, verbose_name='Container Type'),
        ),
        migrations.AlterField(
            model_name='freedaycombination',
            name='container_size',
            field=models.CharField(choices=[('20', '20 ft Standard'), ('20HC', '20 ft High Cube'), ('40', '40 ft Standard'), ('40HC', '40 ft High Cube'), ('45', '45 ft High Cube'), ('any', 'any')], max_length=50),
        ),
        migrations.AlterField(
            model_name='terminalservice',
            name='container_size',
            field=models.CharField(choices=[('20', '20 ft Standard'), ('20HC', '20 ft High Cube'), ('40', '40 ft Standard'), ('40HC', '40 ft High Cube'), ('45', '45 ft High Cube'), ('any', 'any')], default='ANY', max_length=50),
        ),
    ]
