# Generated by Django 5.0.7 on 2024-10-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_terminalservice_multiple_usable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminalservice',
            old_name='multiple_usable',
            new_name='multiple_usage',
        ),
    ]
