# Generated by Django 5.0.7 on 2024-09-26 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='container_documents')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Container Document',
                'verbose_name_plural': 'Container Documents',
                'db_table': 'container_document',
            },
        ),
        migrations.CreateModel(
            name='ContainerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='container_images')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Container Image',
                'verbose_name_plural': 'Container Images',
                'db_table': 'container_image',
            },
        ),
        migrations.CreateModel(
            name='ContainerStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_state', models.CharField(choices=[('loaded', 'loaded'), ('empty', 'empty')], max_length=10)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('container_owner', models.CharField(blank=True, default='', max_length=255)),
                ('transport_type', models.CharField(blank=True, choices=[('auto', 'auto'), ('wagon', 'wagon')], max_length=255)),
                ('transport_number', models.CharField(blank=True, default='', max_length=255)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_transport_type', models.CharField(blank=True, choices=[('auto', 'auto'), ('wagon', 'wagon')], max_length=255, null=True)),
                ('exit_transport_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Container Storage',
                'verbose_name_plural': 'Container Storages',
                'db_table': 'container_storage',
                'ordering': ['-entry_time'],
            },
        ),
    ]
