# Generated by Django 5.0.7 on 2024-09-26 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstorage',
            name='active_services',
            field=models.ManyToManyField(blank=True, related_name='containers', to='customers.contractservice'),
        ),
        migrations.AddField(
            model_name='containerstorage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_visits', to='customers.company'),
        ),
        migrations.AddField(
            model_name='containerstorage',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='core.container'),
        ),
        migrations.AddField(
            model_name='containerstorage',
            name='container_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_visits', to='locations.containerlocation'),
        ),
        migrations.AddField(
            model_name='containerstorage',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_visits', to='customers.companycontract'),
        ),
        migrations.AddField(
            model_name='containerstorage',
            name='dispatch_services',
            field=models.ManyToManyField(blank=True, related_name='dispatched_containers', to='customers.contractservice'),
        ),
        migrations.AddField(
            model_name='containerimage',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='containers.containerstorage'),
        ),
        migrations.AddField(
            model_name='containerdocument',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='containers.containerstorage'),
        ),
    ]
