# Generated by Django 5.0.7 on 2024-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerstorage',
            name='container_state',
            field=models.CharField(choices=[('loaded', 'loaded'), ('empty', 'empty'), ('any', 'any')], max_length=10),
        ),
    ]
