# Generated by Django 5.0.7 on 2024-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_remove_containerstorage_active_services_and_more'),
        ('customers', '0008_companycontract_free_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerstorage',
            name='active_services',
            field=models.ManyToManyField(blank=True, related_name='containers', to='customers.contractservice'),
        ),
    ]
