# Generated by Django 5.0.7 on 2024-10-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_containerstorage_active_services'),
        ('customers', '0008_companycontract_free_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContainerService',
            new_name='ContainerServiceInstance',
        ),
        migrations.AlterModelTable(
            name='containerserviceinstance',
            table='container_service_instance',
        ),
    ]
