# Generated by Django 5.0.7 on 2024-10-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_rename_containerservice_containerserviceinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerserviceinstance',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='containerserviceinstance',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
