# Generated by Django 5.0.7 on 2024-10-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_containerserviceinstance_date_from_and_more'),
        ('customers', '0008_companycontract_free_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerserviceinstance',
            options={'ordering': ['-id'], 'verbose_name': 'Container Service', 'verbose_name_plural': 'Container Services'},
        ),
        migrations.AlterField(
            model_name='containerserviceinstance',
            name='contract_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_instance_services', to='customers.contractservice'),
        ),
    ]
