on:
  push:
    branches:
      - master
jobs:
  build:
    environment:
      name: testing
    env:
      DATABASE_URL: postgres://postgres:1998@localhost:5432/terminal
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASS }}
          POSTGRES_DB: localhost
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Pulling Git Repo
        uses: actions/checkout@v3  # Updated to v3

      - name: Install Python version 3.12
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: "3.12"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install All Dependencies
        run: pip install -r requirements.txt

      - name: Sync Database
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests
        run: |
          pip install pytest
          pytest --junitxml=junit/test-results.xml

  build-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set Tag in Env Variable
        run: |
          echo "${GITHUB_SHA:0:7}" > TAG
          echo "docker.interrail.uz:7007/${{ github.event.repository.name }}" > IMAGE_NAME

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag $(cat IMAGE_NAME):$(cat TAG)

      - name: Docker Login
        run: docker login docker.interrail.uz:7007 -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Image Push
        run: docker push $(cat IMAGE_NAME):$(cat TAG)
